services:
  # A Docker web service
  - type: web
    name: postgres-fastapi
    runtime: python
    plan: free
    autoDeploy: True
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT